version: '2'
services:
  db:
    container_name: mysql
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_USER=ttrss
      - MYSQL_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=ttrss
    volumes:
      - db-data:/var/lib/mysql
  php:
    container_name: php
    image: php:5-fpm-alpine
    links:
      - db
    volumes:
      - ./html:/var/www/html
  web:
    container_name: web
    image: nginx:stable-alpine
    ports:
      - "80:80" 
    links:
      - php
    volumes: 
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
volumes:
  db-data:
    driver: local

