# vim: set ft=dockerfile:
FROM  php:5-fpm-alpine

MAINTAINER YAMASAKI Masahide <masahide.y@gmail.com>

RUN apk --no-cache add \
		php5-json \
		php5-iconv \
		php5-pgsql \
		php5-dom \
		php5-curl \
		php5-mcrypt \
		openssl 

